# Generated by Django 6.0 on 2025-12-28 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
                ('company_location', models.CharField(max_length=100)),
                ('company_website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number_of_openings', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField(help_text='List the required skills, separated by commas')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobportal_App.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('employer', 'Employer'), ('job_seeker', 'Job Seeker')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(help_text='List your skills, separated by commas')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Jobportal_App.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Jobportal_App.userprofile'),
        ),
    ]
