# Generated by Django 6.0 on 2025-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal_App', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
